DROP DATABASE IF EXISTS ECOHUB;
CREATE DATABASE ECOHUB;
USE ECOHUB;

-- Tabela USUARIO
	CREATE TABLE USUARIOS (
		ID VARCHAR(36) PRIMARY KEY, -- Guid
		NOME VARCHAR(255) NOT NULL,
		CPF VARCHAR(14) UNIQUE NOT NULL,
		DATA_NASCIMENTO DATETIME NOT NULL,
		EMAIL VARCHAR(255) UNIQUE NOT NULL,
		SENHA VARCHAR(255) NOT NULL
	);

-- Tabela MATERIAIS
CREATE TABLE MATERIAIS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) UNIQUE NOT NULL,
    DESCRICAO TEXT
);

-- Tabela PONTO_DE_COLETA
CREATE TABLE PONTOS_DE_COLETA (
    ID VARCHAR(36) PRIMARY KEY UNIQUE, -- Guid
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    IMAGEM TEXT,
    NUMERO VARCHAR(10) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    LATITUDE VARCHAR(60) NOT NULL,
    LONGITUDE VARCHAR(60) NOT NULL,
	PONTO_DE_REFERENCIA VARCHAR(500),
    CEP VARCHAR(8) NOT NULL,
    USUARIO_ID VARCHAR(36), -- Guid
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);

-- TABELA MATERIAIS_PONTOS_DE_COLETA (novo formato tabela)

CREATE TABLE MATERIAIS_PONTOS_DE_COLETA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PONTO_DE_COLETA_ID VARCHAR(36),
    MATERIAL_ID INT,
    FOREIGN KEY (PONTO_DE_COLETA_ID) REFERENCES PONTOS_DE_COLETA(ID),
    FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAIS(ID)
);

SELECT * FROM USUARIOS;
SELECT * FROM MATERIAIS;
SELECT * FROM PONTOS_DE_COLETA; 